# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/HK6/Project1/testing/matmul_array/matmul/matmul.runs/synth_1/.Xil/Vivado-11052-VuDuong-32/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xck26-sfvc784-2LV-c
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl 
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    rt::set_parameter singleFileBasedDefaultNettype false
    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/a0fe/hdl
    d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/f0b6/hdl/verilog
    d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/00fe/hdl/verilog
    D:/Apps/Study/Vivado/2025.2/Vivado/data/rsb/busdef
  } {
      D:/Apps/Study/Vivado/2025.2/Vivado/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/Apps/Study/Vivado/2025.2/Vivado/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      D:/Apps/Study/Vivado/2025.2/Vivado/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/0848/hdl/sc_switchboard_v1_0_vl_rfs.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_2/synth/bd_31d6_arinsw_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_3/synth/bd_31d6_rinsw_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_4/synth/bd_31d6_awinsw_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_5/synth/bd_31d6_winsw_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_6/synth/bd_31d6_binsw_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_7/synth/bd_31d6_aroutsw_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_8/synth/bd_31d6_routsw_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_9/synth/bd_31d6_awoutsw_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_10/synth/bd_31d6_woutsw_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_11/synth/bd_31d6_boutsw_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/00fe/hdl/sc_node_v1_0_vl_rfs.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_12/synth/bd_31d6_arni_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_13/synth/bd_31d6_rni_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_14/synth/bd_31d6_awni_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_15/synth/bd_31d6_wni_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_16/synth/bd_31d6_bni_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/3d9a/hdl/sc_mmu_v1_0_vl_rfs.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_17/synth/bd_31d6_s00mmu_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/7785/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_18/synth/bd_31d6_s00tr_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/3051/hdl/sc_si_converter_v1_0_vl_rfs.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_19/synth/bd_31d6_s00sic_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/852f/hdl/sc_axi2sc_v1_0_vl_rfs.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_20/synth/bd_31d6_s00a2s_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_21/synth/bd_31d6_sarn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_22/synth/bd_31d6_srn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_23/synth/bd_31d6_sawn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_24/synth/bd_31d6_swn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_25/synth/bd_31d6_sbn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_26/synth/bd_31d6_s01mmu_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_27/synth/bd_31d6_s01tr_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_28/synth/bd_31d6_s01sic_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_29/synth/bd_31d6_s01a2s_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_30/synth/bd_31d6_sarn_1.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_31/synth/bd_31d6_srn_1.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_32/synth/bd_31d6_sawn_1.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_33/synth/bd_31d6_swn_1.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_34/synth/bd_31d6_sbn_1.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/fca9/hdl/sc_sc2axi_v1_0_vl_rfs.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_35/synth/bd_31d6_m00s2a_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_36/synth/bd_31d6_m00arn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_37/synth/bd_31d6_m00rn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_38/synth/bd_31d6_m00awn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_39/synth/bd_31d6_m00wn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_40/synth/bd_31d6_m00bn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/e44a/hdl/sc_exit_v1_0_vl_rfs.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_41/synth/bd_31d6_m00e_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_42/synth/bd_31d6_m01s2a_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_43/synth/bd_31d6_m01arn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_44/synth/bd_31d6_m01rn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_45/synth/bd_31d6_m01awn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_46/synth/bd_31d6_m01wn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_47/synth/bd_31d6_m01bn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_48/synth/bd_31d6_m01e_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_49/synth/bd_31d6_m02s2a_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_50/synth/bd_31d6_m02arn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_51/synth/bd_31d6_m02rn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_52/synth/bd_31d6_m02awn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_53/synth/bd_31d6_m02wn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_54/synth/bd_31d6_m02bn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_55/synth/bd_31d6_m02e_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_2/synth/bd_90f7_arsw_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_3/synth/bd_90f7_rsw_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_4/synth/bd_90f7_awsw_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_5/synth/bd_90f7_wsw_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_6/synth/bd_90f7_bsw_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_7/synth/bd_90f7_s00mmu_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_8/synth/bd_90f7_s00tr_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_9/synth/bd_90f7_s00sic_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_10/synth/bd_90f7_s00a2s_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_11/synth/bd_90f7_sarn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_12/synth/bd_90f7_srn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_13/synth/bd_90f7_s02mmu_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_14/synth/bd_90f7_s02tr_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_15/synth/bd_90f7_s02sic_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_16/synth/bd_90f7_s02a2s_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_17/synth/bd_90f7_sarn_1.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_18/synth/bd_90f7_srn_1.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_19/synth/bd_90f7_s03mmu_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_20/synth/bd_90f7_s03tr_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_21/synth/bd_90f7_s03sic_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_22/synth/bd_90f7_s03a2s_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_23/synth/bd_90f7_sawn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_24/synth/bd_90f7_swn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_25/synth/bd_90f7_sbn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_26/synth/bd_90f7_m00s2a_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_27/synth/bd_90f7_m00arn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_28/synth/bd_90f7_m00rn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_29/synth/bd_90f7_m00awn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_30/synth/bd_90f7_m00wn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_31/synth/bd_90f7_m00bn_0.sv
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_32/synth/bd_90f7_m00e_0.sv
    }
      rt::read_verilog -include {
    d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/a0fe/hdl
    d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/f0b6/hdl/verilog
    d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/00fe/hdl/verilog
    D:/Apps/Study/Vivado/2025.2/Vivado/data/rsb/busdef
  } {
      D:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/hdl/gemm_block_wrapper.v
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/synth/gemm_block.v
    }
      rt::read_verilog -include {
    d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/a0fe/hdl
    d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/f0b6/hdl/verilog
    d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/00fe/hdl/verilog
    D:/Apps/Study/Vivado/2025.2/Vivado/data/rsb/busdef
  } {
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_zynq_ultra_ps_e_0_0/hdl/zynq_ultra_ps_e_v3_5_8.v
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_zynq_ultra_ps_e_0_0/synth/gemm_block_zynq_ultra_ps_e_0_0.v
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/830a/matmul/matmul.srcs/sources_1/imports/sources_1/new/mac_acc_stage.v
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/830a/matmul/matmul.srcs/sources_1/imports/sources_1/imports/new/mac_core.v
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/830a/matmul/matmul.srcs/sources_1/imports/sources_1/new/mac_mult_stage.v
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/830a/matmul/matmul.srcs/sources_1/imports/sources_1/imports/new/matmul_array.v
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/830a/matmul/matmul.srcs/sources_1/new/output_serializer.v
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/830a/matmul/matmul.srcs/sources_1/imports/sources_1/imports/new/pe_wrapper.v
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/830a/matmul/matmul.srcs/sources_1/new/sc_fifo.v
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/830a/matmul/matmul.srcs/sources_1/new/sc_fifo_fwft.v
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/830a/src/shift_register_delay.v
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/830a/src/skew_network.v
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/830a/src/systolic_dataflow_ctrl.v
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/830a/src/gemm_accelerator.v
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_gemm_accelerator_0_0/synth/gemm_block_gemm_accelerator_0_0.v
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/synth/bd_31d6.v
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/synth/gemm_block_axi_smc_0.v
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/synth/bd_90f7.v
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/synth/gemm_block_axi_smc_1_0.v
    }
      rt::read_vhdl -lib xpm D:/Apps/Study/Vivado/2025.2/Vivado/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -lib axi_datamover_v5_1_37 d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/d44a/hdl/axi_datamover_v5_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_sg_v4_1_21 d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/b193/hdl/axi_sg_v4_1_rfs.vhd
      rt::read_vhdl -lib axi_dma_v7_1_37 d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/7f6a/hdl/axi_dma_v7_1_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_dma_0_0/synth/gemm_block_axi_dma_0_0.vhd
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_1/synth/bd_31d6_psr_aclk_0.vhd
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_rst_ps8_0_99M_0/synth/gemm_block_rst_ps8_0_99M_0.vhd
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_dma_1_0/synth/gemm_block_axi_dma_1_0.vhd
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_1/synth/bd_90f7_psr_aclk_0.vhd
      d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_gpio_0_0/synth/gemm_block_axi_gpio_0_0.vhd
    }
      rt::read_vhdl -lib proc_sys_reset_v5_0_17 d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/9438/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib axi_lite_ipif_v3_0_4 d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib interrupt_control_v3_1_5 d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/d8cc/hdl/interrupt_control_v3_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_gpio_v2_0_37 d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ipshared/0271/hdl/axi_gpio_v2_0_vh_rfs.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList D:/HK6/Project1/testing/matmul_array/matmul/matmul.runs/synth_1/.Xil/Vivado-11052-VuDuong-32/realtime/gemm_block_wrapper_synth.xdc
    rt::sdcChecksum
    set rt::top gemm_block_wrapper
    rt::set_parameter incrementalOnCache "D:/HK6/Project1/testing/matmul_array/matmul/matmul.runs/synth_1/.Xil/Vivado-11052-VuDuong-32/refSynth"
    rt::set_parameter doIncremental true
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {D:/HK6/Project1/testing/matmul_array/matmul/matmul.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "D:/HK6/Project1/testing/matmul_array/matmul/matmul.runs/synth_1/.Xil/Vivado-11052-VuDuong-32/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    rt::set_parameter incrementalOnCache ""
    rt::set_parameter doIncremental false
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   if {[info exists rt::doParallel] && $rt::doParallel} {
     rt::async_wait "asyncParallelOpen"
     rt::parallel_close
   }
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  }
 return -code "error" $rt::result
}
