# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/gemm_block_v1/gemm_block_v1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_block_v1 || ORIG_REF_NAME==gemm_block_v1} -quiet] -quiet

# IP: bd/gemm_block_v1/ip/gemm_block_v1_zynq_ultra_ps_e_0_0/gemm_block_v1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_block_v1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==gemm_block_v1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/gemm_block_v1/ip/gemm_block_v1_gemm_accelerator_0_0/gemm_block_v1_gemm_accelerator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_block_v1_gemm_accelerator_0_0 || ORIG_REF_NAME==gemm_block_v1_gemm_accelerator_0_0} -quiet] -quiet

# IP: bd/gemm_block_v1/ip/gemm_block_v1_axi_dma_0_0/gemm_block_v1_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_block_v1_axi_dma_0_0 || ORIG_REF_NAME==gemm_block_v1_axi_dma_0_0} -quiet] -quiet

# IP: bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/gemm_block_v1_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_block_v1_axi_smc_0 || ORIG_REF_NAME==gemm_block_v1_axi_smc_0} -quiet] -quiet

# IP: bd/gemm_block_v1/ip/gemm_block_v1_rst_ps8_0_99M_0/gemm_block_v1_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_block_v1_rst_ps8_0_99M_0 || ORIG_REF_NAME==gemm_block_v1_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/gemm_block_v1/ip/gemm_block_v1_axi_dma_1_0/gemm_block_v1_axi_dma_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_block_v1_axi_dma_1_0 || ORIG_REF_NAME==gemm_block_v1_axi_dma_1_0} -quiet] -quiet

# IP: bd/gemm_block_v1/ip/gemm_block_v1_axi_gpio_0_0/gemm_block_v1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_block_v1_axi_gpio_0_0 || ORIG_REF_NAME==gemm_block_v1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_1_0/gemm_block_v1_axi_smc_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_block_v1_axi_smc_1_0 || ORIG_REF_NAME==gemm_block_v1_axi_smc_1_0} -quiet] -quiet

# IP: bd/gemm_block_v1/ip/gemm_block_v1_xlconcat_0_0/gemm_block_v1_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_block_v1_xlconcat_0_0 || ORIG_REF_NAME==gemm_block_v1_xlconcat_0_0} -quiet] -quiet

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/gemm_block_v1_ooc.xdc
