# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/E/1subject/HK6/doan1/int8-matmul-accelerator/gemm_accelerator/gemm_accelerator.srcs/sources_1/bd/gemm_system/ip/gemm_system_axi_datamover_0_0/gemm_system_axi_datamover_0_0.xci
# IP: The module: 'gemm_system_axi_datamover_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/E/1subject/HK6/doan1/int8-matmul-accelerator/gemm_accelerator/gemm_accelerator.gen/sources_1/bd/gemm_system/ip/gemm_system_axi_datamover_0_0/gemm_system_axi_datamover_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gemm_system_axi_datamover_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/E/1subject/HK6/doan1/int8-matmul-accelerator/gemm_accelerator/gemm_accelerator.gen/sources_1/bd/gemm_system/ip/gemm_system_axi_datamover_0_0/gemm_system_axi_datamover_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'gemm_system_axi_datamover_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/E/1subject/HK6/doan1/int8-matmul-accelerator/gemm_accelerator/gemm_accelerator.gen/sources_1/bd/gemm_system/ip/gemm_system_axi_datamover_0_0/gemm_system_axi_datamover_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gemm_system_axi_datamover_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/E/1subject/HK6/doan1/int8-matmul-accelerator/gemm_accelerator/gemm_accelerator.srcs/sources_1/bd/gemm_system/ip/gemm_system_axi_datamover_0_0/gemm_system_axi_datamover_0_0.xci
# IP: The module: 'gemm_system_axi_datamover_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/E/1subject/HK6/doan1/int8-matmul-accelerator/gemm_accelerator/gemm_accelerator.gen/sources_1/bd/gemm_system/ip/gemm_system_axi_datamover_0_0/gemm_system_axi_datamover_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gemm_system_axi_datamover_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/E/1subject/HK6/doan1/int8-matmul-accelerator/gemm_accelerator/gemm_accelerator.gen/sources_1/bd/gemm_system/ip/gemm_system_axi_datamover_0_0/gemm_system_axi_datamover_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'gemm_system_axi_datamover_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/E/1subject/HK6/doan1/int8-matmul-accelerator/gemm_accelerator/gemm_accelerator.gen/sources_1/bd/gemm_system/ip/gemm_system_axi_datamover_0_0/gemm_system_axi_datamover_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gemm_system_axi_datamover_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
