# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/E/1subject/HK6/doan1/ver1/matmul/matmul.srcs/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_gemm_accelerator_0_0/gemm_block_v1_gemm_accelerator_0_0.xci
# IP: The module: 'gemm_block_v1_gemm_accelerator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/E/1subject/HK6/doan1/ver1/matmul/matmul.srcs/sources_1/ip/fifo_512_to_128/fifo_512_to_128.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_512_to_128 || ORIG_REF_NAME==fifo_512_to_128} -quiet] -quiet

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_gemm_accelerator_0_0/gemm_block_v1_gemm_accelerator_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gemm_block_v1_gemm_accelerator_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/E/1subject/HK6/doan1/ver1/matmul/matmul.srcs/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_gemm_accelerator_0_0/gemm_block_v1_gemm_accelerator_0_0.xci
# IP: The module: 'gemm_block_v1_gemm_accelerator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/E/1subject/HK6/doan1/ver1/matmul/matmul.srcs/sources_1/ip/fifo_512_to_128/fifo_512_to_128.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_512_to_128 || ORIG_REF_NAME==fifo_512_to_128} -quiet] -quiet

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_gemm_accelerator_0_0/gemm_block_v1_gemm_accelerator_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gemm_block_v1_gemm_accelerator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
