# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/gemm_block/gemm_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_block || ORIG_REF_NAME==gemm_block} -quiet] -quiet

# IP: bd/gemm_block/ip/gemm_block_zynq_ultra_ps_e_0_0/gemm_block_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_block_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==gemm_block_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/gemm_block/ip/gemm_block_axi_dma_0_0/gemm_block_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_block_axi_dma_0_0 || ORIG_REF_NAME==gemm_block_axi_dma_0_0} -quiet] -quiet

# IP: bd/gemm_block/ip/gemm_block_gemm_accelerator_0_0/gemm_block_gemm_accelerator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_block_gemm_accelerator_0_0 || ORIG_REF_NAME==gemm_block_gemm_accelerator_0_0} -quiet] -quiet

# IP: bd/gemm_block/ip/gemm_block_axi_smc_0/gemm_block_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_block_axi_smc_0 || ORIG_REF_NAME==gemm_block_axi_smc_0} -quiet] -quiet

# Block Designs: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/bd_31d6.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_1/bd_31d6_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_2/bd_31d6_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_3/bd_31d6_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_4/bd_31d6_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_5/bd_31d6_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_6/bd_31d6_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_7/bd_31d6_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_8/bd_31d6_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_9/bd_31d6_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_10/bd_31d6_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_11/bd_31d6_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_12/bd_31d6_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_13/bd_31d6_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_14/bd_31d6_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_15/bd_31d6_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_16/bd_31d6_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_17/bd_31d6_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_18/bd_31d6_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_19/bd_31d6_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_20/bd_31d6_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_21/bd_31d6_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_22/bd_31d6_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_23/bd_31d6_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_24/bd_31d6_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_25/bd_31d6_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_26/bd_31d6_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_27/bd_31d6_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_28/bd_31d6_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_29/bd_31d6_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_30/bd_31d6_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_31/bd_31d6_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_32/bd_31d6_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_33/bd_31d6_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_34/bd_31d6_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_35/bd_31d6_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_36/bd_31d6_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_37/bd_31d6_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_38/bd_31d6_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_39/bd_31d6_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_40/bd_31d6_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_41/bd_31d6_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_42/bd_31d6_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_43/bd_31d6_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_44/bd_31d6_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_45/bd_31d6_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_46/bd_31d6_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_47/bd_31d6_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_48/bd_31d6_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_49/bd_31d6_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_50/bd_31d6_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_51/bd_31d6_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_52/bd_31d6_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_53/bd_31d6_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_54/bd_31d6_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_55/bd_31d6_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/gemm_block/ip/gemm_block_rst_ps8_0_99M_0/gemm_block_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_block_rst_ps8_0_99M_0 || ORIG_REF_NAME==gemm_block_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/gemm_block/ip/gemm_block_axi_dma_1_0/gemm_block_axi_dma_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_block_axi_dma_1_0 || ORIG_REF_NAME==gemm_block_axi_dma_1_0} -quiet] -quiet

# IP: bd/gemm_block/ip/gemm_block_axi_smc_1_0/gemm_block_axi_smc_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_block_axi_smc_1_0 || ORIG_REF_NAME==gemm_block_axi_smc_1_0} -quiet] -quiet

# Block Designs: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/bd_90f7.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_1/bd_90f7_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_2/bd_90f7_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_3/bd_90f7_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_4/bd_90f7_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_5/bd_90f7_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_6/bd_90f7_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_7/bd_90f7_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_8/bd_90f7_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_9/bd_90f7_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_10/bd_90f7_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_11/bd_90f7_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_12/bd_90f7_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_13/bd_90f7_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_14/bd_90f7_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_15/bd_90f7_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_16/bd_90f7_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_17/bd_90f7_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_18/bd_90f7_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_19/bd_90f7_s03mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_20/bd_90f7_s03tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_21/bd_90f7_s03sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_22/bd_90f7_s03a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_23/bd_90f7_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_24/bd_90f7_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_25/bd_90f7_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_26/bd_90f7_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_27/bd_90f7_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_28/bd_90f7_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_29/bd_90f7_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_30/bd_90f7_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_31/bd_90f7_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_32/bd_90f7_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/gemm_block/ip/gemm_block_axi_gpio_0_0/gemm_block_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_block_axi_gpio_0_0 || ORIG_REF_NAME==gemm_block_axi_gpio_0_0} -quiet] -quiet

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_zynq_ultra_ps_e_0_0/gemm_block_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_zynq_ultra_ps_e_0_0/gemm_block_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==gemm_block_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==gemm_block_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_dma_0_0/gemm_block_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==gemm_block_axi_dma_0_0 || ORIG_REF_NAME==gemm_block_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_dma_0_0/gemm_block_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==gemm_block_axi_dma_0_0 || ORIG_REF_NAME==gemm_block_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_1/bd_31d6_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_2/bd_31d6_arinsw_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_3/bd_31d6_rinsw_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_4/bd_31d6_awinsw_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_5/bd_31d6_winsw_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_6/bd_31d6_binsw_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_7/bd_31d6_aroutsw_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_8/bd_31d6_routsw_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_9/bd_31d6_awoutsw_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_10/bd_31d6_woutsw_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_11/bd_31d6_boutsw_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_12/bd_31d6_arni_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_13/bd_31d6_rni_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_14/bd_31d6_awni_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_15/bd_31d6_wni_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_16/bd_31d6_bni_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_20/bd_31d6_s00a2s_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_21/bd_31d6_sarn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_22/bd_31d6_srn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_23/bd_31d6_sawn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_24/bd_31d6_swn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_25/bd_31d6_sbn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_29/bd_31d6_s01a2s_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_30/bd_31d6_sarn_1_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_31/bd_31d6_srn_1_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_32/bd_31d6_sawn_1_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_33/bd_31d6_swn_1_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_34/bd_31d6_sbn_1_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_35/bd_31d6_m00s2a_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_36/bd_31d6_m00arn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_37/bd_31d6_m00rn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_38/bd_31d6_m00awn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_39/bd_31d6_m00wn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_40/bd_31d6_m00bn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_42/bd_31d6_m01s2a_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_43/bd_31d6_m01arn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_44/bd_31d6_m01rn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_45/bd_31d6_m01awn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_46/bd_31d6_m01wn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_47/bd_31d6_m01bn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_49/bd_31d6_m02s2a_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_50/bd_31d6_m02arn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_51/bd_31d6_m02rn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_52/bd_31d6_m02awn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_53/bd_31d6_m02wn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/bd_0/ip/ip_54/bd_31d6_m02bn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==gemm_block_axi_smc_0 || ORIG_REF_NAME==gemm_block_axi_smc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_rst_ps8_0_99M_0/gemm_block_rst_ps8_0_99M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==gemm_block_rst_ps8_0_99M_0 || ORIG_REF_NAME==gemm_block_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_dma_1_0/gemm_block_axi_dma_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==gemm_block_axi_dma_1_0 || ORIG_REF_NAME==gemm_block_axi_dma_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_dma_1_0/gemm_block_axi_dma_1_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==gemm_block_axi_dma_1_0 || ORIG_REF_NAME==gemm_block_axi_dma_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_1/bd_90f7_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_2/bd_90f7_arsw_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_3/bd_90f7_rsw_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_4/bd_90f7_awsw_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_5/bd_90f7_wsw_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_6/bd_90f7_bsw_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_10/bd_90f7_s00a2s_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_11/bd_90f7_sarn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_12/bd_90f7_srn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_16/bd_90f7_s02a2s_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_17/bd_90f7_sarn_1_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_18/bd_90f7_srn_1_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_22/bd_90f7_s03a2s_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_23/bd_90f7_sawn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_24/bd_90f7_swn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_25/bd_90f7_sbn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_26/bd_90f7_m00s2a_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_27/bd_90f7_m00arn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_28/bd_90f7_m00rn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_29/bd_90f7_m00awn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_30/bd_90f7_m00wn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/bd_0/ip/ip_31/bd_90f7_m00bn_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_smc_1_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==gemm_block_axi_smc_1_0 || ORIG_REF_NAME==gemm_block_axi_smc_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_gpio_0_0/gemm_block_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==gemm_block_axi_gpio_0_0 || ORIG_REF_NAME==gemm_block_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/ip/gemm_block_axi_gpio_0_0/gemm_block_axi_gpio_0_0_ooc.xdc

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/gemm_block/gemm_block_ooc.xdc
