# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/HK6/Project1/testing/accumulator/accumulator/accumulator.srcs/sources_1/bd/acc_block/ip/acc_block_zynq_ultra_ps_e_0_0/acc_block_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'acc_block_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/HK6/Project1/testing/accumulator/accumulator/accumulator.gen/sources_1/bd/acc_block/ip/acc_block_zynq_ultra_ps_e_0_0/acc_block_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'acc_block_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/HK6/Project1/testing/accumulator/accumulator/accumulator.gen/sources_1/bd/acc_block/ip/acc_block_zynq_ultra_ps_e_0_0/acc_block_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'acc_block_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/HK6/Project1/testing/accumulator/accumulator/accumulator.srcs/sources_1/bd/acc_block/ip/acc_block_zynq_ultra_ps_e_0_0/acc_block_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'acc_block_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/HK6/Project1/testing/accumulator/accumulator/accumulator.gen/sources_1/bd/acc_block/ip/acc_block_zynq_ultra_ps_e_0_0/acc_block_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'acc_block_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/HK6/Project1/testing/accumulator/accumulator/accumulator.gen/sources_1/bd/acc_block/ip/acc_block_zynq_ultra_ps_e_0_0/acc_block_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'acc_block_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
