# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/E/1subject/HK6/doan1/ver1/matmul/matmul.srcs/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/gemm_block_v1_axi_smc_0.xci
# IP: The module: 'gemm_block_v1_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/bd_5f09.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_1/bd_5f09_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_2/bd_5f09_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_3/bd_5f09_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_4/bd_5f09_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_5/bd_5f09_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_6/bd_5f09_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_7/bd_5f09_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_8/bd_5f09_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_9/bd_5f09_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_10/bd_5f09_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_11/bd_5f09_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_12/bd_5f09_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_13/bd_5f09_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_14/bd_5f09_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_15/bd_5f09_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_16/bd_5f09_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_17/bd_5f09_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_18/bd_5f09_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_19/bd_5f09_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_20/bd_5f09_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_21/bd_5f09_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_22/bd_5f09_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_23/bd_5f09_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_24/bd_5f09_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_25/bd_5f09_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_26/bd_5f09_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_27/bd_5f09_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_28/bd_5f09_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_29/bd_5f09_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_30/bd_5f09_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_31/bd_5f09_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_32/bd_5f09_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_33/bd_5f09_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_34/bd_5f09_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_35/bd_5f09_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_36/bd_5f09_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_37/bd_5f09_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_38/bd_5f09_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_39/bd_5f09_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_40/bd_5f09_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_41/bd_5f09_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_42/bd_5f09_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_43/bd_5f09_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_44/bd_5f09_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_45/bd_5f09_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_46/bd_5f09_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_47/bd_5f09_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_48/bd_5f09_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_49/bd_5f09_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_50/bd_5f09_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_51/bd_5f09_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_52/bd_5f09_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_53/bd_5f09_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_54/bd_5f09_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_55/bd_5f09_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_1/bd_5f09_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_2/bd_5f09_arinsw_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_3/bd_5f09_rinsw_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_4/bd_5f09_awinsw_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_5/bd_5f09_winsw_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_6/bd_5f09_binsw_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_7/bd_5f09_aroutsw_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_8/bd_5f09_routsw_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_9/bd_5f09_awoutsw_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_10/bd_5f09_woutsw_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_11/bd_5f09_boutsw_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_12/bd_5f09_arni_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_13/bd_5f09_rni_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_14/bd_5f09_awni_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_15/bd_5f09_wni_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_16/bd_5f09_bni_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_20/bd_5f09_s00a2s_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_21/bd_5f09_sarn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_22/bd_5f09_srn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_23/bd_5f09_sawn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_24/bd_5f09_swn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_25/bd_5f09_sbn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_29/bd_5f09_s01a2s_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_30/bd_5f09_sarn_1_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_31/bd_5f09_srn_1_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_32/bd_5f09_sawn_1_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_33/bd_5f09_swn_1_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_34/bd_5f09_sbn_1_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_35/bd_5f09_m00s2a_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_36/bd_5f09_m00arn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_37/bd_5f09_m00rn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_38/bd_5f09_m00awn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_39/bd_5f09_m00wn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_40/bd_5f09_m00bn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_42/bd_5f09_m01s2a_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_43/bd_5f09_m01arn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_44/bd_5f09_m01rn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_45/bd_5f09_m01awn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_46/bd_5f09_m01wn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_47/bd_5f09_m01bn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_49/bd_5f09_m02s2a_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_50/bd_5f09_m02arn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_51/bd_5f09_m02rn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_52/bd_5f09_m02awn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_53/bd_5f09_m02wn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_54/bd_5f09_m02bn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gemm_block_v1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'gemm_block_v1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/E/1subject/HK6/doan1/ver1/matmul/matmul.srcs/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/gemm_block_v1_axi_smc_0.xci
# IP: The module: 'gemm_block_v1_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/bd_5f09.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_1/bd_5f09_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_2/bd_5f09_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_3/bd_5f09_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_4/bd_5f09_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_5/bd_5f09_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_6/bd_5f09_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_7/bd_5f09_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_8/bd_5f09_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_9/bd_5f09_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_10/bd_5f09_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_11/bd_5f09_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_12/bd_5f09_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_13/bd_5f09_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_14/bd_5f09_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_15/bd_5f09_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_16/bd_5f09_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_17/bd_5f09_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_18/bd_5f09_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_19/bd_5f09_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_20/bd_5f09_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_21/bd_5f09_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_22/bd_5f09_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_23/bd_5f09_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_24/bd_5f09_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_25/bd_5f09_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_26/bd_5f09_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_27/bd_5f09_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_28/bd_5f09_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_29/bd_5f09_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_30/bd_5f09_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_31/bd_5f09_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_32/bd_5f09_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_33/bd_5f09_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_34/bd_5f09_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_35/bd_5f09_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_36/bd_5f09_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_37/bd_5f09_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_38/bd_5f09_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_39/bd_5f09_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_40/bd_5f09_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_41/bd_5f09_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_42/bd_5f09_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_43/bd_5f09_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_44/bd_5f09_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_45/bd_5f09_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_46/bd_5f09_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_47/bd_5f09_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_48/bd_5f09_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_49/bd_5f09_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_50/bd_5f09_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_51/bd_5f09_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_52/bd_5f09_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_53/bd_5f09_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_54/bd_5f09_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_55/bd_5f09_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_1/bd_5f09_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_2/bd_5f09_arinsw_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_3/bd_5f09_rinsw_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_4/bd_5f09_awinsw_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_5/bd_5f09_winsw_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_6/bd_5f09_binsw_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_7/bd_5f09_aroutsw_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_8/bd_5f09_routsw_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_9/bd_5f09_awoutsw_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_10/bd_5f09_woutsw_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_11/bd_5f09_boutsw_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_12/bd_5f09_arni_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_13/bd_5f09_rni_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_14/bd_5f09_awni_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_15/bd_5f09_wni_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_16/bd_5f09_bni_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_20/bd_5f09_s00a2s_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_21/bd_5f09_sarn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_22/bd_5f09_srn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_23/bd_5f09_sawn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_24/bd_5f09_swn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_25/bd_5f09_sbn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_29/bd_5f09_s01a2s_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_30/bd_5f09_sarn_1_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_31/bd_5f09_srn_1_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_32/bd_5f09_sawn_1_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_33/bd_5f09_swn_1_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_34/bd_5f09_sbn_1_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_35/bd_5f09_m00s2a_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_36/bd_5f09_m00arn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_37/bd_5f09_m00rn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_38/bd_5f09_m00awn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_39/bd_5f09_m00wn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_40/bd_5f09_m00bn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_42/bd_5f09_m01s2a_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_43/bd_5f09_m01arn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_44/bd_5f09_m01rn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_45/bd_5f09_m01awn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_46/bd_5f09_m01wn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_47/bd_5f09_m01bn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_49/bd_5f09_m02s2a_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_50/bd_5f09_m02arn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_51/bd_5f09_m02rn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_52/bd_5f09_m02awn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_53/bd_5f09_m02wn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/bd_0/ip/ip_54/bd_5f09_m02bn_0_ooc.xdc

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gemm_block_v1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/bd/gemm_block_v1/ip/gemm_block_v1_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'gemm_block_v1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
