# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.srcs/sources_1/ip/fifo_512_to_128/fifo_512_to_128.xci
# IP: The module: 'fifo_512_to_128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/ip/fifo_512_to_128/fifo_512_to_128.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_512_to_128'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/ip/fifo_512_to_128/fifo_512_to_128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_512_to_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.srcs/sources_1/ip/fifo_512_to_128/fifo_512_to_128.xci
# IP: The module: 'fifo_512_to_128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/ip/fifo_512_to_128/fifo_512_to_128.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_512_to_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/E/1subject/HK6/doan1/ver1/matmul/matmul.gen/sources_1/ip/fifo_512_to_128/fifo_512_to_128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_512_to_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
