# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/HK6/Project1/testing/mul_reg/mul_reg/mul_reg.srcs/sources_1/bd/mul_block/ip/mul_block_axi_gpio_0_0/mul_block_axi_gpio_0_0.xci
# IP: The module: 'mul_block_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/HK6/Project1/testing/mul_reg/mul_reg/mul_reg.gen/sources_1/bd/mul_block/ip/mul_block_axi_gpio_0_0/mul_block_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mul_block_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/HK6/Project1/testing/mul_reg/mul_reg/mul_reg.gen/sources_1/bd/mul_block/ip/mul_block_axi_gpio_0_0/mul_block_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mul_block_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/HK6/Project1/testing/mul_reg/mul_reg/mul_reg.srcs/sources_1/bd/mul_block/ip/mul_block_axi_gpio_0_0/mul_block_axi_gpio_0_0.xci
# IP: The module: 'mul_block_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/HK6/Project1/testing/mul_reg/mul_reg/mul_reg.gen/sources_1/bd/mul_block/ip/mul_block_axi_gpio_0_0/mul_block_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mul_block_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/HK6/Project1/testing/mul_reg/mul_reg/mul_reg.gen/sources_1/bd/mul_block/ip/mul_block_axi_gpio_0_0/mul_block_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mul_block_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
