# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/array_block/array_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==array_block || ORIG_REF_NAME==array_block} -quiet] -quiet

# IP: bd/array_block/ip/array_block_array_top_0_0/array_block_array_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==array_block_array_top_0_0 || ORIG_REF_NAME==array_block_array_top_0_0} -quiet] -quiet

# IP: bd/array_block/ip/array_block_zynq_ultra_ps_e_0_0/array_block_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==array_block_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==array_block_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/array_block/ip/array_block_axi_gpio_0_0/array_block_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==array_block_axi_gpio_0_0 || ORIG_REF_NAME==array_block_axi_gpio_0_0} -quiet] -quiet

# IP: bd/array_block/ip/array_block_smartconnect_0_0/array_block_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==array_block_smartconnect_0_0 || ORIG_REF_NAME==array_block_smartconnect_0_0} -quiet] -quiet

# IP: bd/array_block/ip/array_block_proc_sys_reset_0_0/array_block_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==array_block_proc_sys_reset_0_0 || ORIG_REF_NAME==array_block_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/array_block/ip/array_block_xlslice_0_0/array_block_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==array_block_xlslice_0_0 || ORIG_REF_NAME==array_block_xlslice_0_0} -quiet] -quiet

# IP: bd/array_block/ip/array_block_xlslice_1_0/array_block_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==array_block_xlslice_1_0 || ORIG_REF_NAME==array_block_xlslice_1_0} -quiet] -quiet

# IP: bd/array_block/ip/array_block_xlslice_2_0/array_block_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==array_block_xlslice_2_0 || ORIG_REF_NAME==array_block_xlslice_2_0} -quiet] -quiet

# XDC: d:/HK6/Project1/testing/matmul_array/matmul/matmul.gen/sources_1/bd/array_block/array_block_ooc.xdc
