# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/mul_block/mul_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mul_block || ORIG_REF_NAME==mul_block} -quiet] -quiet

# IP: bd/mul_block/ip/mul_block_mul_pu_0_0/mul_block_mul_pu_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mul_block_mul_pu_0_0 || ORIG_REF_NAME==mul_block_mul_pu_0_0} -quiet] -quiet

# IP: bd/mul_block/ip/mul_block_zynq_ultra_ps_e_0_0/mul_block_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mul_block_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==mul_block_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/mul_block/ip/mul_block_rst_ps8_0_99M_0/mul_block_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mul_block_rst_ps8_0_99M_0 || ORIG_REF_NAME==mul_block_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/mul_block/ip/mul_block_axi_gpio_0_0/mul_block_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mul_block_axi_gpio_0_0 || ORIG_REF_NAME==mul_block_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mul_block/ip/mul_block_xlslice_0_0/mul_block_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mul_block_xlslice_0_0 || ORIG_REF_NAME==mul_block_xlslice_0_0} -quiet] -quiet

# IP: bd/mul_block/ip/mul_block_xlslice_1_0/mul_block_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mul_block_xlslice_1_0 || ORIG_REF_NAME==mul_block_xlslice_1_0} -quiet] -quiet

# IP: bd/mul_block/ip/mul_block_xlslice_2_0/mul_block_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mul_block_xlslice_2_0 || ORIG_REF_NAME==mul_block_xlslice_2_0} -quiet] -quiet

# IP: bd/mul_block/ip/mul_block_axi_smc_1/mul_block_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mul_block_axi_smc_1 || ORIG_REF_NAME==mul_block_axi_smc_1} -quiet] -quiet

# XDC: d:/HK6/Project1/testing/mul_reg/mul_reg/mul_reg.gen/sources_1/bd/mul_block/mul_block_ooc.xdc
