# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/acc_block/acc_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==acc_block || ORIG_REF_NAME==acc_block} -quiet] -quiet

# IP: bd/acc_block/ip/acc_block_acc_reg_0_0/acc_block_acc_reg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==acc_block_acc_reg_0_0 || ORIG_REF_NAME==acc_block_acc_reg_0_0} -quiet] -quiet

# IP: bd/acc_block/ip/acc_block_zynq_ultra_ps_e_0_0/acc_block_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==acc_block_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==acc_block_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/acc_block/ip/acc_block_xlslice_0_0/acc_block_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==acc_block_xlslice_0_0 || ORIG_REF_NAME==acc_block_xlslice_0_0} -quiet] -quiet

# IP: bd/acc_block/ip/acc_block_xlslice_1_0/acc_block_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==acc_block_xlslice_1_0 || ORIG_REF_NAME==acc_block_xlslice_1_0} -quiet] -quiet

# IP: bd/acc_block/ip/acc_block_xlslice_2_0/acc_block_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==acc_block_xlslice_2_0 || ORIG_REF_NAME==acc_block_xlslice_2_0} -quiet] -quiet

# IP: bd/acc_block/ip/acc_block_axi_gpio_0_0/acc_block_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==acc_block_axi_gpio_0_0 || ORIG_REF_NAME==acc_block_axi_gpio_0_0} -quiet] -quiet

# IP: bd/acc_block/ip/acc_block_axi_smc_0/acc_block_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==acc_block_axi_smc_0 || ORIG_REF_NAME==acc_block_axi_smc_0} -quiet] -quiet

# IP: bd/acc_block/ip/acc_block_rst_ps8_0_99M_0/acc_block_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==acc_block_rst_ps8_0_99M_0 || ORIG_REF_NAME==acc_block_rst_ps8_0_99M_0} -quiet] -quiet

# XDC: d:/HK6/Project1/testing/accumulator/accumulator/accumulator.gen/sources_1/bd/acc_block/acc_block_ooc.xdc
