# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/HK6/Project1/testing/accumulator/accumulator/accumulator.srcs/sources_1/bd/acc_block/ip/acc_block_rst_ps8_0_99M_0/acc_block_rst_ps8_0_99M_0.xci
# IP: The module: 'acc_block_rst_ps8_0_99M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/HK6/Project1/testing/accumulator/accumulator/accumulator.gen/sources_1/bd/acc_block/ip/acc_block_rst_ps8_0_99M_0/acc_block_rst_ps8_0_99M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'acc_block_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/HK6/Project1/testing/accumulator/accumulator/accumulator.gen/sources_1/bd/acc_block/ip/acc_block_rst_ps8_0_99M_0/acc_block_rst_ps8_0_99M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'acc_block_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/HK6/Project1/testing/accumulator/accumulator/accumulator.srcs/sources_1/bd/acc_block/ip/acc_block_rst_ps8_0_99M_0/acc_block_rst_ps8_0_99M_0.xci
# IP: The module: 'acc_block_rst_ps8_0_99M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/HK6/Project1/testing/accumulator/accumulator/accumulator.gen/sources_1/bd/acc_block/ip/acc_block_rst_ps8_0_99M_0/acc_block_rst_ps8_0_99M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'acc_block_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/HK6/Project1/testing/accumulator/accumulator/accumulator.gen/sources_1/bd/acc_block/ip/acc_block_rst_ps8_0_99M_0/acc_block_rst_ps8_0_99M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'acc_block_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
