# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/gemm_system/gemm_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_system || ORIG_REF_NAME==gemm_system} -quiet] -quiet

# IP: bd/gemm_system/ip/gemm_system_gemm_top_l2_0_0/gemm_system_gemm_top_l2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_system_gemm_top_l2_0_0 || ORIG_REF_NAME==gemm_system_gemm_top_l2_0_0} -quiet] -quiet

# IP: bd/gemm_system/ip/gemm_system_gemm_l2_axi_lite_regs_0_0/gemm_system_gemm_l2_axi_lite_regs_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_system_gemm_l2_axi_lite_regs_0_0 || ORIG_REF_NAME==gemm_system_gemm_l2_axi_lite_regs_0_0} -quiet] -quiet

# IP: bd/gemm_system/ip/gemm_system_zynq_ultra_ps_e_0_0/gemm_system_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_system_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==gemm_system_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/gemm_system/ip/gemm_system_axi_datamover_0_0/gemm_system_axi_datamover_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_system_axi_datamover_0_0 || ORIG_REF_NAME==gemm_system_axi_datamover_0_0} -quiet] -quiet

# IP: bd/gemm_system/ip/gemm_system_xlconcat_0_0/gemm_system_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_system_xlconcat_0_0 || ORIG_REF_NAME==gemm_system_xlconcat_0_0} -quiet] -quiet

# IP: bd/gemm_system/ip/gemm_system_rst_ps8_0_99M_1/gemm_system_rst_ps8_0_99M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_system_rst_ps8_0_99M_1 || ORIG_REF_NAME==gemm_system_rst_ps8_0_99M_1} -quiet] -quiet

# IP: bd/gemm_system/ip/gemm_system_smartconnect_0_1/gemm_system_smartconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_system_smartconnect_0_1 || ORIG_REF_NAME==gemm_system_smartconnect_0_1} -quiet] -quiet

# IP: bd/gemm_system/ip/gemm_system_smartconnect_1_0/gemm_system_smartconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_system_smartconnect_1_0 || ORIG_REF_NAME==gemm_system_smartconnect_1_0} -quiet] -quiet

# IP: bd/gemm_system/ip/gemm_system_axi_smc_2/gemm_system_axi_smc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_system_axi_smc_2 || ORIG_REF_NAME==gemm_system_axi_smc_2} -quiet] -quiet

# XDC: d:/E/1subject/HK6/doan1/int8-matmul-accelerator/gemm_accelerator/gemm_accelerator.gen/sources_1/bd/gemm_system/gemm_system_ooc.xdc
